"""
Django settings for axf project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!tsfh4%q2=abake_f)@3ua95&@noxf%e7^ix8*t-2*h9vl6pvt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'App',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #自定义中间件验证验证码
    # 'Middleware.yzmMiddleware.YZMMiddle',
    #自定义用户验证中间件
    'Middleware.userAccountMiddleware.UserAccountMiddle',
    #自定义头像上传验证
    'Middleware.iconMiddleware.IconMiddle',
    #添加商品到购物车
    'Middleware.isLoginMiddleware.isLoginMiddle',
]

ROOT_URLCONF = 'axf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'axf.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'axf',
        'HOST': '121.4.50.115',
        'POST': '3306',
        'USER': 'wen',
        'PASSWORD':'123',

    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

#配置字体库文件位置
FONTS_DIRS = os.path.join(BASE_DIR, 'App/static/mine/fonts')

# oss云存储
ACCESS_KEY_ID = 'LTAI4G2BHwnXztBkfxGycb5x'
ACCESS_KEY_SECRET = 'BHR6uwbzgUPy5fh7PaE7FfHxU16pI7'

#设置模型类
AUTH_USER_MODEL = 'App.User'

from django.shortcuts import redirect,reverse
#登录端点设置
LOGIN_URL = '/login/'
#设置上传头像类型
ALLOWED_FILES = ['jpg','jpeg','png']

#支付宝设置
APP_ID = '2016110300789682'
APP_PRIVATE_KEY_STRING = open(os.path.join(BASE_DIR,'alipayConfig/private.txt')).read()
ALIPAY_PUBLIC_KEY_STRING = open(os.path.join(BASE_DIR,'alipayConfig/public.txt')).read()