# Generated by Django 2.2.3 on 2020-12-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20201216_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=10, verbose_name='商品id')),
                ('productimg', models.CharField(max_length=100, verbose_name='商品图片')),
                ('productname', models.CharField(max_length=30, verbose_name='商品名称')),
                ('productlongname', models.CharField(max_length=50, verbose_name='商品的长名称')),
                ('isxf', models.BooleanField(verbose_name='是否精选')),
                ('pmdesc', models.BooleanField(verbose_name='是否买一赠一')),
                ('specifics', models.CharField(max_length=10, verbose_name='规格')),
                ('price', models.CharField(max_length=10, verbose_name='价格')),
                ('marketprice', models.CharField(max_length=10, verbose_name='超市价格')),
                ('categoryid', models.CharField(max_length=10, verbose_name='类别id')),
                ('childcid', models.CharField(max_length=10, verbose_name='子类别id')),
                ('childcidname', models.CharField(max_length=10, verbose_name='子类别名称')),
                ('dealerid', models.CharField(max_length=10, verbose_name='详情页id')),
                ('storenums', models.IntegerField(verbose_name='库存')),
                ('productnum', models.IntegerField(verbose_name='销量')),
            ],
            options={
                'db_table': 'axf_goods',
            },
        ),
        migrations.AlterField(
            model_name='foodtypes',
            name='childtypenames',
            field=models.CharField(max_length=120, verbose_name='子类别id和名称'),
        ),
        migrations.AlterField(
            model_name='foodtypes',
            name='typeid',
            field=models.CharField(max_length=10, verbose_name='类别id'),
        ),
        migrations.AlterField(
            model_name='foodtypes',
            name='typename',
            field=models.CharField(max_length=10, verbose_name='类别名称'),
        ),
        migrations.AlterField(
            model_name='foodtypes',
            name='typesort',
            field=models.IntegerField(verbose_name='排序字段'),
        ),
    ]
