# Generated by Django 2.2.3 on 2020-12-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
