# Generated by Django 2.2.3 on 2020-12-23 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Goods', verbose_name='商品一对多关系'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='isChoose',
            field=models.BooleanField(default=False, verbose_name='商品在购物车中是否选中'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='num',
            field=models.IntegerField(default=1, verbose_name='购物车商品数量'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户一对多关系'),
        ),
    ]
