# Generated by Django 2.2.3 on 2020-12-23 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_auto_20201223_0258'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='axf_cart',
        ),
    ]
