# Generated by Django 2.2.3 on 2020-12-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20201223_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='selectAll',
            field=models.BooleanField(default=False, verbose_name='是否全选'),
        ),
    ]
