# Generated by Django 2.2.3 on 2020-12-27 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_auto_20201225_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单总金额')),
                ('message', models.CharField(max_length=100, verbose_name='买家留言')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('orderId', models.CharField(max_length=64, verbose_name='订单ID')),
                ('state', models.BooleanField(default=False, verbose_name='订单状态')),
            ],
            options={
                'db_table': 'axf_order',
            },
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=200, verbose_name='地址详情'),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=20, verbose_name='接收人'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.BooleanField(default=False, verbose_name='默认地址'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to=settings.AUTH_USER_MODEL, verbose_name='一对多'),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsImg', models.CharField(max_length=100, verbose_name='商品图片')),
                ('goodsName', models.CharField(max_length=50, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品单价')),
                ('num', models.IntegerField(default=1, verbose_name='商品数量')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Order', verbose_name='订单外键')),
            ],
            options={
                'db_table': 'axf_orderDetail',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Address', verbose_name='地址外键'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户外键'),
        ),
    ]
