# Generated by Django 2.2.3 on 2020-12-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_auto_20201227_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isDelete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
